- namespace: privileged.remoteSettings
  description: Remote Settings

  functions:
  - name: clearLocalDataAndForceSync
    type: function
    description: Triggers a synchronization at the level only for the specified collection
    async: true
    parameters:
    - name: collection
      type: string
      description: collection name
  - name: fetchFromEndpointDirectly
    type: function
    description: Fetch the data for the specified collection by querying the remote settings endpoint directly
    async: true
    parameters:
    - name: collection
      type: string
      description: collection name
